[package]
name = "matdoesdev-protocols"
version = "0.1.14"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
async-recursion = "1.0.4"
byteorder = "1.4.3"
chrono = { version = "0.4.24", features = ["serde"] }
curve25519-dalek = "4.0.0"
ed25519-dalek = "1.0.1"
futures-util = "0.3.28"
html-escape = "0.2.13"
mime_guess = "2.0.4"
rand = "0.8.5"
rand_os = "0.2.2"
rcgen = "0.10.0"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
sha2 = "0.10.7"
tl = "0.7.7"
tokio = { version = "1.27.0", features = ["full"] }
tokio-rustls = "0.24.0"
tokio-util = { version = "0.7.8", features = ["codec"] }
url = "2.3.1"
