[package]
name = "matdoesdev-protocols"
version = "0.1.13"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
chrono = { version = "0.4.24", features = ["serde"] }
html-escape = "0.2.13"
mime_guess = "2.0.4"
rcgen = "0.10.0"
reqwest = { version = "0.11.16", features = ["json"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tl = "0.7.7"
tokio = { version = "1.27.0", features = ["full"] }
tokio-rustls = "0.24.0"
url = "2.3.1"
